# configs/config.yaml
defaults:
  - command: null
model:
  inference_dir: inference
  num_trials: 100
  dir: "models"
  file_name: "rf_model.joblib"
  random_state: 42
  n_iter: 10
  cv: 5
  n_estimators: [100, 200, 300]
  max_depth: [5, 10, 20, 30]
  num_trees: [50, 100, 200]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]
  test_size: 0.2

tensorboard:
  dir: tensorboard_logs
  uri: "http://128.0.1.2:8080"

mlflow:
  uri: "http://127.0.1.1:8080"
scaler:
  file_name: "scaler.joblib"

data:
  train_path: "data/train.csv"
  inference_path: "data/test.csv"
  target_column: "quality"

